language: ruby
rvm:
  - 2.2.4
  - jruby-9.1.5.0
gemfile:
  - Gemfile
  - test/gemfiles/activerecord32.gemfile
  - test/gemfiles/activerecord40.gemfile
  - test/gemfiles/activerecord41.gemfile
  - test/gemfiles/activerecord42.gemfile
sudo: false
script: RUBYOPT=W0 bundle exec rake test
before_install:
  - gem install bundler
  - mysql -e 'create database groupdate_test;'
  - mysql_tzinfo_to_sql /usr/share/zoneinfo | mysql -u root mysql
  - psql -c 'create database groupdate_test;' -U postgres
addons:
  apt:
    sources:
      - travis-ci/sqlite3
    packages:
      - sqlite3
notifications:
  email:
    on_success: never
    on_failure: change
matrix:
  allow_failures:
    - rvm: jruby-9.1.5.0
      gemfile: Gemfile
