dist: bionic
language: ruby
rvm: 2.6
gemfile:
  - Gemfile
  - test/gemfiles/activerecord52.gemfile
  - test/gemfiles/activerecord51.gemfile
  - test/gemfiles/activerecord50.gemfile
services:
  - postgresql
  - mysql
addons:
  postgresql: 10
script: bundle exec rake test
before_install:
  - mysqladmin create groupdate_test
  - mysql_tzinfo_to_sql /usr/share/zoneinfo | mysql -u root mysql
  - createdb groupdate_test
notifications:
  email:
    on_success: never
    on_failure: change
